"""implement alembic

Revision ID: 60d813ef4579
Revises: 
Create Date: 2024-06-13 23:33:07.645877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60d813ef4579'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_ibfk_2', 'categories', type_='foreignkey')
    op.drop_column('categories', 'note')
    op.alter_column('notes', 'slug',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_notes_title', table_name='notes')
    op.create_index(op.f('ix_notes_slug'), 'notes', ['slug'], unique=False)
    op.drop_constraint('notes_ibfk_3', 'notes', type_='foreignkey')
    op.drop_constraint('notes_ibfk_1', 'notes', type_='foreignkey')
    op.drop_column('notes', 'category')
    op.drop_column('notes', 'tag')
    op.drop_constraint('tags_ibfk_2', 'tags', type_='foreignkey')
    op.drop_column('tags', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('note', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_ibfk_2', 'tags', 'notes', ['note'], ['id'])
    op.add_column('notes', sa.Column('tag', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('category', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notes_ibfk_1', 'notes', 'tags', ['tag'], ['id'])
    op.create_foreign_key('notes_ibfk_3', 'notes', 'categories', ['category'], ['id'])
    op.drop_index(op.f('ix_notes_slug'), table_name='notes')
    op.create_index('ix_notes_title', 'notes', ['title'], unique=False)
    op.alter_column('notes', 'slug',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('categories', sa.Column('note', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_ibfk_2', 'categories', 'notes', ['note'], ['id'])
    # ### end Alembic commands ###
